### ISSUE TITLE
Send many for arbitrary fungible token

### ISSUE THREAD

**Issue by badonyx** [friedger/stacks-send-many#33]
Instead of specializing for specific tokens, it would be helpful to have a send-many function that can work with any provided token contract. ~~Similarly it would be helpful to have a send-many function for sending many NFTs by ID from any provided NFT collection.~~

**Comment by friedger** [comment]
Thank you for the suggestion. Could you split these into two issues, please?

Currently, we don't have support for NFTs at all, it is a different story with image handling, etc.

Using arbitrary fungible tokens is easier to implement because the UI is already very customized for different tokens.

How would users select the token?

**Comment by friedger** [comment]
We could add liquid stacking tokens and meme tokens.

**Comment by badonyx** [comment]
It does not need a fancy token selection UI, just an input form for the token contract would suffice.

**Comment by badonyx** [comment]
NFT feature request moved to #43

**Comment by friedger** [comment]
The code has been updated to easily add more tokens. For each new token, we need to configure which send-many function to use.

![image](https://github.com/user-attachments/assets/3c4e6fc3-dc4d-4a0c-8192-a02d2ce8c219)

Feel free to request specific tokens.
